# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8256d38ebfaf13d173fa3cf6b4e1e4d19f790a9efb4f62be5f69d47a3bb482fec5928d532648aed34ab95ea964eb969784c2b539e9df0b28cbaa982a66e5f150

test:
  secret_key_base: 6f8b7a40ddf61d52a059cecbfe4296202abb421372ac51c7ff4497c64c0c7ee7b87dbf3b35ea8ae2bd2446bbbaf123ee265e9096d806922acb7e444fb5528f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
